### DISCUSSION TITLE
How to correctly set up SparkDataSet using S3

### DISCUSSION THREAD

**Discussion by paulofbmarcon** [kedro-org/kedro#1352] [Idea]
I tried the below configuration in catalog.yml but I couldn't login to AWS S3. The only way I could get to access s3 files was to set com.amazonaws.auth.profile.ProfileCredentialsProvider in spark.yml. Is this the expected behavior? 
It looks like SparkDataSet should be reading my credentials configuration file.

```
some_database:
  type: spark.SparkDataSet
  filepath: s3a://some-bucket/somepath/hugefile.csv
  credentials: dev_s3
  file_format: csv
  load_args:
    delimiter: ";"
    header: "True"
    inferSchema: True
    overwrite: "True"
```
with the credentials.yml as follow:

```
dev_s3:
  key: "mykey"
  secret: "mysecrect"
```
