### DISCUSSION TITLE
How do I specify multiple data folders with in catalog.yml file?

### DISCUSSION THREAD

**Discussion by ghost** [kedro-org/kedro#1894] [Idea]
Hello, 

I wanted to know if there is a way to specify multiple data folders in the catalog.yml file
At the moment my data storage has a root folder which has one folder corresponding to each date like - 2022-09-30, 2022-10-01... etc. and internally each date folder has many parquet files.
I was able to load the multiple parquet files corresponding to one date folder in this way using the PartitionedDataSet-

```
type: PartitionedDataSet
path: "/Users/praneeth/Desktop/data/2022-09-30"
dataset: pandas.ParquetDataSet
load_args:
  engine: pyarrow
  use_nullable_dtypes: True
```

Can anyone suggest me if there is a way to load the specified folders instead of a single folder? (for e.g -> to load all the folders between 2022-09-26 till 2022-10-03)
Ideally I wanted to load the last 7 day folders based on the current date

Thank you!!
