### DISCUSSION TITLE
Config validation

### DISCUSSION THREAD

**Discussion by astrojuanlu** [kedro-org/kedro#3788] [Idea]
## Description
Today I spoke to a user that had a very long and treacherous `parameters.yml` like this:

```yaml
sensors:
  sensor1:
    name: "Sensor 1"
    type: "temperature"
    stderr: 0.1
  sensor2:
    name: "Sensor 2"
    type: "humidity"
    stderr: 0.1
  sensor3:
    name: "Sensor 3"
    type: "temperature"
    stderr: 0.1
  sensor4:
    name: "Sensor 4"
    type: "temperature"
    stderr: 0.2
```

And so forth. So, there are several problems:

1. There's lots of repetition. The user mentioned that it would be ideal to be able to "inherit" in YAML, something like:

```yaml
_sensor:
  type: "<unknown>"
  stderr: 0.1

sensors:
  sensor1: ${_sensor}  # All defaults are taken
  sensor2: ${_sensor}
    stderr: 0.2  # Try to override default, but 💥 syntax error
```

2. It's unclear how to validate this YAML. We did a quick proof of concept combining OmegaConf and Pydantic v2:

```python
from omegaconf import OmegaConf
from pydantic import BaseModel

class Sensor(BaseModel):
    name: str
    sensor_type: str = "<unknown>"
    stderr: t.Optional[float] = 0.1

class Config(BaseModel):
    sensors: t.Dict[str, Sensor]

config = OmegaConf.load("conf/base/parameters.yml")
c = Config.validate(config)
print(c.sensors["sensor3"].stderr)
```

Which was cool! Because the defaults were filled from the `Sensor` model.

However, (2a) it's not clear how to keep the defaults in the YAML, which was desirable (although there's maybe a way to achieve that in Pydantic), (2b) it's not clear if this should be in `parameters.yml` or rather a custom `sensors.yml`, and most importantly, (2c) it's not clear how or where to perform such validation. There's no `after_config_loaded` hook.

I think the closest might be what kedro-mlflow does using `after_context_created` https://github.com/Galileo-Galilei/kedro-mlflow/blob/e88679938b1d4c7633c3f631f6b402ff11ab61fe/kedro_mlflow/framework/hooks/mlflow_hook.py#L78-L79 but then it's trying to inject the config in the `KedroContext` https://github.com/Galileo-Galilei/kedro-mlflow/blob/e88679938b1d4c7633c3f631f6b402ff11ab61fe/kedro_mlflow/framework/hooks/mlflow_hook.py#L129-L134, with all the problems discussed in #3214.

How can we better support this use case?

Paging @datajoely, @Galileo-Galilei

**Comment by astrojuanlu** [comment]
Tangentially related: https://github.com/kedro-org/kedro/issues/2481

**Comment by datajoely** [comment]
So we actually have a solution for config inheritance and mixins in some of our internal tooling (hopefully open sourcing in 2024 🤞) for assembling Kedro projects.

It's proven a useful feature for achieving DRY concepts, powered by OmegaConf and Python devs find it easy to grok since it follows [MRO](https://www.python.org/download/releases/2.3/mro/) to the dot.

For QB contributors I can link to the [docs](https://brix.quantumblack.com/products/alloy/docs/04_working_with_alloy/app/configuring/#extends-liststr) and the [specific implementation](https://github.com/McK-Internal/verticalx-alloy/blob/88684d5d8d64c6c09a4d59b53aa462b45aaa8088/alloy/core/yaml_config.py#L187) here. 

Please find a screenshot of the docs of the `extends` keyword below:

![image](https://github.com/kedro-org/kedro/assets/35801847/3cdd8f67-8187-4351-a60b-c96e30b8d11e)

|At rest|Run-time resolved|
|-|-|
|![image](https://github.com/kedro-org/kedro/assets/35801847/c7d3188e-278f-4f55-9b24-3080ecdc534a)| ![image](https://github.com/kedro-org/kedro/assets/35801847/58e88352-7eb4-4f37-9bfd-50d231759dbf)|

As well as a `mixin` concept:

![image](https://github.com/kedro-org/kedro/assets/35801847/d58c8f8a-ad77-4d7c-84b0-368d32fc3f85)

|At rest|Run-time resolved|
|-|-|
|![image](https://github.com/kedro-org/kedro/assets/35801847/5c0651b4-1ed0-4017-96db-ce4c72cdf81b)|![image](https://github.com/kedro-org/kedro/assets/35801847/75db7cc4-3ce4-4e2f-9e0e-837fd57f9753)|

**Comment by datajoely** [comment]
Regarding validation I would actually apply the Pydantic models to the functions bound in the node function - not couple it to the configuration system.

**Comment by Galileo-Galilei** [comment]
This is indeed a question that have been asked a couple of times. Apart from this specific use case (where it may eventually makes sense to have a specific configuration file as you suggest), my usual go to solution is to create a custom resolver,  which would look like this: 

```yaml
_sensor:
  type: "<unknown>"
  stderr: 0.1

_sensor2:
  stderr: 0.2

sensors:
  sensor1: ${_sensor}  # All defaults are taken
  sensor2: ${merge_dict: _sensor, _sensor2} # in settings. py : register_new_resolver("merge_dict", lambda d1, d2: {**d1, **d2})
```

We could probably make the syntax easier with a more complex resolution logic (e.g. find if the key exists in a parent node to "automatically" check for a parent key with the same name (look for ``_parent_`` on this page https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html), and to validate the results with pydantic.

**Comment by noklam** [comment]
Apple rolls their own DSL for configuration

https://github.com/apple/pkl

**Comment by datajoely** [comment]
>Apple rolls their own DSL for configuration
> https://github.com/apple/pkl

So I find the niche space of "Configuration languages" like [Jsonnet](https://jsonnet.org/), [Dhall](https://dhall-lang.org/), [Cue](https://cuelang.org/) and now pkl super interesting. I've posted [this before](https://sre.google/workbook/configuration-specifics/) but it's genuinely one of the best articles on how all the lessons learned in the K8s world apply here. I think #891 is the bible on this and ultimately lays out why we ultimately settled on `OmegaConf` (I was pitching Jsonnet at the time). 

I'm more convinced than ever that:

- We should lean into extending `OmegaConf` so that configuration at rest is more powerful (e.g. adding inheritance) 
- For validation we need to lean into Pythonic frameworks on the function/node level like Pydantic and Pandera. This has the added benefit of not being an integration, just best practice.
- (stretch goal) We should explore Viz as a configuration assistant taking the idea of `kedro catalog resolve` further perhaps with side by side config at rest vs runtime

**Comment by astrojuanlu** [comment]
Today, after showing dataset factories to a user:

> Can I restrict the possible values of the `{}` part of the dataset to a specific subset?

**Comment by astrojuanlu** [comment]
BTW the first problem can be trivially solved with YAML merge keys:

```yaml
_default: &default
  name: "Sensor 1"
  type: "temperature"
  stderr: 0.1

sensors:
  sensor1:
    <<: *default

  sensor2:
    <<: *default
    name: "Sensor 2"
    stderr: 0.2
```
