### DISCUSSION TITLE
Make `kedro catalog list-datasets` command support runtime parameters

### DISCUSSION THREAD

**Discussion by ElenaKhaustova** [kedro-org/kedro#5128] [Idea]
## Description
Currently, `kedro catalog list-datasets` does not support inputting runtime parameters.

## Context
If the dataset is defined with runtime parameters, there's no way to provide them via running the command.

```yaml
companies:
    type: pandas.CSVDataset
    filepath: data/01_raw/${runtime_params:companies_basename}.csv
```

This leads to the following error when running the command without arguments:
```console
InterpolationResolutionError: Runtime parameter 'companies_basename' not found and no default value provided.
    full_key: shuttles.filepath
    object_type=dict
```
