### ISSUE TITLE
Using fsspec/dropboxdrivefs makes DataSet gobble up the first directory level

### ISSUE THREAD

**Issue by mjmare** [kedro-org/kedro#1262]
I created a catalog entry: 
```
activiteiten_dropbox:
  layer: intermediate
  type: pickle.PickleDataSet
  filepath: dropbox://dummy/testing/activiteiten_extra.pickle
  credentials: dropbox
```
With the relevant credentials + pipeline.

This all worked fine but the file was written at the path:
```
<MyDropboxFolder>/testing/activiteiten_extra.pickle
```
So the dir _dummy_ has disappeared.
