### ISSUE TITLE
Alter framework logging.yml configuration

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1470]
Various small changes to make to the framework kedro/config/logging.yml (**not to the project conf/base/logging.yml**):
* delete the section `root`
* add the `kedro.io` and `kedro.pipeline` that are in project conf/base/logging.yml to the framework kedro/config/logging.yml 
* add the following to the loggers:
```
kedro:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]
  propagate: no
```

Do some kedro runs to make sure things look ok. I'm pretty sure they will.
