### ISSUE TITLE
[KED-2783] Decide how to declare the explicit dependency between micro-packages

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1478]
(transfer from Jira, created by @lorenabalan)

Once all the imports in (issue above) are converted and everything is packaged up, there's a chance some micro-packages depend on each other. Following the same example of 

 
```toml
[tool.kedro.pipeline.package]
"pipelines.alpha" = {alias = beta}
"pipelines.alpha.utils" = {alias = sigma}
"other_package" = {alias = utilities, destination = "dist/libraries"}
```

*beta* could be importing something from *other_package* and therefore there's a dependency between the two, that's very likely not expressed in the modular pipeline's requirements.txt. How do we make sure this link is captured? In the metadata of the resulting source distribution of *beta*? In the contents of the distribution, i.e. packaged together? Should *other_package* come as source code or directly as wheel?
