### ISSUE TITLE
Datasets are being not feeded with credentials

### ISSUE THREAD

**Issue by ElCuboNegro** [kedro-org/kedro#1523]
## Description
Catalog APIDataSet is not feeded with Api-Key when it's declared on the credentials file, noted that that behavior comes from multiple contexts and happens all the times the auth key is different than 'credentials' 
## Context
Can't connect with an API that has a `unique-url-as-user` // `header : {Api-Key:  <Key>}` authentication format

## Steps to Reproduce
1. In catalog:  
```
API_AC_ACCOUNTS:
  type: api.APIDataSet
  url: https://<api_url>.api-us1.com/api/3/accounts
  method: GET
  headers:
    Api-Key:
     sn_credentials
  params:
    Accept: application/json
```

2. in credentials.yml
```
sn_credentials: uasjunpfns8-9dfaoisd9fiusapdhfjp8asdf-whatever
```
## Expected Result
the credentials should be injected on the API_AC_ACCOUNTS

```
API_AC_ACCOUNTS:
  type: api.APIDataSet
  url: https://<api_url>.api-us1.com/api/3/accounts
  method: GET
  headers:
    Api-Key: uasjunpfns8-9dfaoisd9fiusapdhfjp8asdf-whatever
  params:
    Accept: application/json
```

## Actual Result
Error 403, the header delivered to the server was

```
API_AC_ACCOUNTS:
  type: api.APIDataSet
  url: https://<api_url>.api-us1.com/api/3/accounts
  method: GET
  headers:
    Api-Key:
     sn_credentials
  params:
    Accept: application/json
```

## Your Environment
Kedro 18.1
Python 3.8
Windows 11

**Comment by AntonyMilneQB** [comment]
Hello @ElCuboNegro. The issue here is that `credentials` is a sort of special keyword in kedro, and entries from credentials.yml are only injected into a catalog entry when that `credentials` keyword is used. Hence `Api-Key` won't get recognised as a key that should inject credentials.

`APIDataSet` already has a `credentials` argument, so the best way to do this would be to make your own custom `APIDataSet` that inherits from this, takes the value injected into `credentials` and relabels the key to `Api-Key`. Something like this should do it:
```
class MyAPIDataSet(APIDataSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "credentials" in self._request_args["headers"]:
            self._request_args["headers"]["Api-Key"] = self._request_args["headers"].pop("credentials")
```

Then in your catalog entry you'd do:
```
API_AC_ACCOUNTS:
  type: api.APIDataSet
  url: https://<api_url>.api-us1.com/api/3/accounts
  method: GET
  headers:
    credentials: sn_credentials
  params:
    Accept: application/json
```
