### ISSUE TITLE
Expand partitioned dataset documentation

### ISSUE THREAD

**Issue by tomvigrass** [kedro-org/kedro#1567]
## Description
Having recently used PartitionedDataSet for spark+parquet, it wasnt immediately clear how to configure this from documentation. I'd like to see additional examples/more complete documentation of the initialisation arguments

## Context
This should speed up others configuring partitioned dataset in similar circumstances

## Possible Implementation
Docs to include an example of a spark+parquet partitioned dataset, specifically noting that parquet use directories rather than files for their paths and these are not picked up with default config. For example:

```
example_partitioned_data:
  type: PartitionedDataSet
  dataset:
    type: spark.SparkDataSet
    file_format: parquet
    save_args:
      mode: overwrite
  path: /dbfs/path/to/folder/
  load_args:
    withdirs: true
  filename_suffix: '.pq'
```

Additionally, this would be benefitted by extra documentation on `filename_suffix`, the present docs do not mention that the suffix is added to all partitions at write.
