### ISSUE TITLE
Poetry Support for Kedro Projects

### ISSUE THREAD

**Issue by DataPsycho** [kedro-org/kedro#1722]
## Description
The way kedro initiate a new project and create the folder structure does not goes well with Poetry . Usually I would create a Poetry environment before doing anything and then install all my required pacakges one by one. After I create a Poetry environment and added the kedro package the pyproject toml looks as followes:

`poetry new --src KedroPoetry`

```toml
[tool.poetry]
name = "KedroPoetry"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
kedro = {version = "~0.18.2", python = ">=3.8,<3.11"}

[tool.poetry.dev-dependencies]
pytest = "^7.1"

... (more lines)
```
Lets run the demo pytest to see if everything works. 

```
poetry run pytest .
```
This goes well:

```
KedroPoetry|⇒ poetry run pytest .
platform darwin -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/ALAMSHC/PythonProjects/KedroPoetry
collected 1 item                                                                                                       

tests/test_kedropoetry.py .                                                                                      [100%]

```
Now its time to add a Kedro Project: `kedro new`

The command completely ignored the current `pyproject.toml` file. and as there is a src file it did not add the project in the src folder instead create a directory on the root outside of src. Now there is no kedro setup section in pyproject.toml so kedro cli will complain for broken setup.

## Context
As Poetry provide one of the modern approach for packaging Python projects it will be good to have direct support for Poetry like project structure for Kedro or at-least a hackable way out will also work.

## Possible Implementation
There could be a new flag in cli to initiate project with Kedro when there is already a pyproject.toml file and a project setup for Poetry.
