### ISSUE TITLE
Can we use dashes in yml syntax for the `config.yml`? 

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1790]
## Introduction

https://github.com/kedro-org/kedro/issues/1485

## Problem

Currently, there are 2 ways to provide argument to `kedro run` CLI.

1. Using the CLI argument `kedro run --from-nodes=some_node`
2. Using the `--config` argument and define the arguments in a YAML file. `kedro run --config=config.yml`

```yml
# config.yml
run:
  from_nodes: some_node # Notice this is underscore instead of a dash
```

## Task
Ideally the YAML config should use the same arguments as the CLI, i.e. using the dash instead of the underscore. Investigate if it's possible to use dashes in `config.yml`. The `click context` handles some of this logic, and so we need to find out if it is possible to use dash in yaml or not. If it is possible, then we'll implement it, but that would be a breaking change.
