### ISSUE TITLE
Document why users need to use underscores for CLI values in `config.yml`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1791]
## Introduction

https://github.com/kedro-org/kedro/issues/1485

## Background

Currently, there are 2 ways to provide argument to `kedro run` CLI.

1. Using the CLI argument `kedro run --from-nodes=some_node`
2. Using the `--config` argument and define the arguments in a YAML file. `kedro run --config=config.yml`

```yml
# config.yml
run:
  from_nodes: some_node # Notice this is underscore instead of a dash
```

## Task

We need to document more clearly that the syntax for CLI arguments is different from the values in `config.yml` and why that's the case.
