### ISSUE TITLE
OmegaConfigLoader does not ignores keys starting with '_'

### ISSUE THREAD

**Issue by zerodarkzone** [kedro-org/kedro#2399]
## Description
OmegaConfigLoader does not ignores keys starting with '\_'. 
Because of this, there are some problems using yaml templates in the catalog.
Kedro tries to instantiate catalog entries starting with '\_' so it is difficult to define partial entries because of missing parameters.

## Context
I'm trying to use the OmegaConfigLoader with yaml templates in the catalog

## Steps to Reproduce
1. Define OmegaConfigLoader as the config loader in the project settings
2. Create a partial yaml template in the catalog definition. ej:
``` yaml
_spark_dataset: &spark_dataset
  type: spark.SparkDataSet
  file_format: delta
```
3. Use the template in a catalog entry.
``` yaml
test_table:
  <<: *spark_dataset
  filepath: <path>
```

## Expected Result
The catalog should have one entry called 'test_table'.

``` python
{
    'test_table': {
        'type': 'spark.SparkDataSet',
        'filepath': 'path', 
        'file_format': 'delta'
    }
}
```
## Actual Result
The catalog tries to instantiate a dataset called '_spark_dataset' and fails because of a missing parameter.

```
kedro.io.core.DataSetError:
__init__() missing 1 required positional argument: 'filepath'.
DataSet '_spark_dataset' must only contain arguments valid for the constructor of 'kedro.extras.datasets.spark.spark_dataset.SparkDataSet'.
```

## Your Environment
* Kedro version: 0.18.6
* Python version: 3.9.16
