### ISSUE TITLE
Prototype parsing rules for dataset factories

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2508]
## Description
Subtask of https://github.com/kedro-org/kedro/issues/2423

## Context
For the dataset factories solution we'll need a way to parse the syntax to match datasets against. 
Parse (https://github.com/r1chardj0n3s/parse) is a library that has a pattern-matching syntax which uses reverse Python f-strings format. 

Example of what our syntax could be:
```yaml
"{root_namespace}.{*}@{spark}":
  type: spark.SparkDataSet
  filepath: data/{chunks[0]}/{chunks[1]}.parquet
  file_format: parquet
```

And the function that would create the dataset entry:
```python
def create_spark_dataset(dataset_name: str, *chunks):
    # e.g. here chunks=["root_namespace", "something-instead-the-*", "spark"]
    return  SparkDataSet(filepath=f"data/{chunks[0]}/{chunks[1]}.parquet", file_format="parquet")
```

## Things to investigate
The goal of this ticket is to experiment with that library and come up with rules on how the matching should work. 

It's especially important to determine what needs to happen when two patterns would match a datasets. E.g. `france.companies@spark` against:

```yaml
"{root_namespace}.{dataset_name}@spark":
  type: spark.SparkDataSet
  filepath: data/{root_namespace}/{dataset_name}.parquet
  file_format: parquet

"{dataset_name}@spark":
  type: spark.SomethingElse
  filepath: data/{dataset_name}.parquet
  file_format: parquet
```

Pattern matching is a common problem in url matching, so take inspiration from web frameworks who solve that problem, e.g. Ruby/React. 

## Initial thoughts on rules
1. The most explicit pattern should match first
2. Then match alphabetically (?)
