### ISSUE TITLE
Saving TensorFlowModelDataset as partition

### ISSUE THREAD

**Issue by anabelchuinard** [kedro-org/kedro#2955]
## Description
Can't save TensorFlowModelDataset objects as partition.

## Context
I am dealing with a project where I have to train several models concurrently. I started writing my code using PartitionedDataset where each partition corresponds to the data relative to one training. When I am trying to save the resulting tensorflow  models as a partition, I get an error. 

This is the instance of my catalog corresponding to the models I want to save:
```
tensorflow_models:
  type: PartitionedDataset
  path: data/derived/ML/models
  filename_suffix: ".h5"
  dataset:
    type: kedro.extras.datasets.tensorflow.TensorFlowModelDataset
```

## Steps to Reproduce
1. Generate a bunch of trained models 
2. Try to save them in a partition as TensorFlowModelDataset objects

## Expected Result
Should create one file per partition with the name of the file being the associate dictionary key.

## Actual Result
Getting this error:
```
DatasetError: Failed while saving data to data set PartitionedDataset(dataset_config={}, dataset_type=TensorFlowModelDataset,
path=...).
The first argument to `Layer.call` must always be passed.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.18.12
* Python version used (`python -V`): 3.9.16
* Operating system and version: Mac M2
