### ISSUE TITLE
New version of `fsspec` breaks load of versioned `TensorflowModelDataset`

### ISSUE THREAD

**Issue by toby-coleman** [kedro-org/kedro#2994]
## Description

I recently upgraded my Python dependencies and found that I could not load a versioned `TensorflowModelDataset`. The error is
```
OSError: SavedModel file does not exist at: 
/var/folders/7c/0cjr9j7j50l2qg_kpcslzyd40000gn/T/kedro_tensorflow_tmpd3lx1c7x/{saved_model.pbtxt|saved_model.pb}
```

## Context

Unable to load dataset until downgraded to `fsspec==2022.1.0`, which I had been using before. I have not tested all the versions in between this and the current `2023.6.0`.

The problem appears to occur at https://github.com/kedro-org/kedro/blob/0293dc15812b27330bba31a01c7b332b3165af2a/kedro/extras/datasets/tensorflow/tensorflow_model_dataset.py#L141C20-L141C20 where `fs.get` is called. The older version of `fsspec` will copy the `saved_model.pb` into the temporary location, whereas `fsspec==2023.6.0` will copy in the `my_test_dataset` subfolder instead.

## Steps to Reproduce

Create a versioned `TensorflowModelDataset`, for example
```yaml
my_test_dataset:
  type: kedro.extras.datasets.tensorflow.TensorFlowModelDataset
  filepath: data/07_model_output/my_test_dataset/
  versioned: true
  layer: model_output
```

The folder structure will be of the form `data/07_model_output/my_test_dataset/2023-06-26T18.41.21.708Z/my_test_dataset` for a specific version.

## Expected Result

Model should be loaded.

## Actual Result

Error as above.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): `kedro, version 0.18.12`
* Python version used (`python -V`): `Python 3.9.18`
* Operating system and version: macOS 13.5
