### ISSUE TITLE
 Partitioned Dataset Lazy Saving [bug/doc]

### ISSUE THREAD

**Issue by cverluiseQB** [kedro-org/kedro#3052]
# Partitioned Dataset Lazy Saving 

## Problem
When using partitioned datasets with lazy saving in Kedro, following the current [documentation example](https://docs.kedro.org/en/0.18.3/data/kedro_io.html#partitioned-dataset-lazy-saving), the key value mapping is messed up. Specifically, the same values is saved for all keys. 

## Expected Behavior
Without lazy loading (lambda), everything works as expected, with keys and values are correctly associated.

## Example

<details><summary>Expand example (on click)</summary>

**Example dataset**

``` shell
! mkdir ../data/01_raw/bug
! parallel 'touch ../data/01_raw/bug/{}.csv' ::: a b c d e f g h i j
! parallel 'echo "{}" >>  ../data/01_raw/bug/{}.csv' ::: a b c d e f g h i j
```

**Example catalog**

``` yml
input_files:
    type: PartitionedDataset
    path: ../data/01_raw/bug/
    dataset: pandas.CSVDataSet
    filename_suffix: .csv
    overwrite: True
    
output_files:
    type: PartitionedDataset
    path: ../data/02_intermediate/bug/
    dataset: pandas.CSVDataSet
    filename_suffix: .csv
    overwrite: True
```

**Example node**

``` py 

def copy_paste(input_loader):
    df = input_loader()
    return df

def copy_paste_node(input_files):
    return {k: lambda: copy_paste(v) for k, v in input_files.items()}

```

**Run node**

``` py 

from kedro.io import DataCatalog

# Create a data catalog from the configuration
conf_catalog = yaml.safe_load(catalog)
data_catalog = DataCatalog.from_config(conf_catalog)

# data input
input_files = data_catalog.load("input_files")
# function call
output_files = copy_paste_node(input_files)
# data output
data_catalog.save("output_files", output_files)

```

**Observe bug**

``` py 
from pathlib import Path

filepaths = Path("../data/02_intermediate/bug/").glob("*.csv")
for filepath in filepaths:
    print(filepath.name, filepath.read_text(), sep=": ")

# a.csv: j -> Expected a.csv: a
# c.csv: j -> Expected c.csv: c
# b.csv: j -> Expected b.csv: b
# f.csv: j -> ...
# g.csv: j
# e.csv: j
# d.csv: j
# i.csv: j
# h.csv: j
# j.csv: j

```

</details>

**Fix**

Complete the lambda with arguments to make it aware of the actual value(s) passed to address the lambda scoping issues.

In our example, this means the following:

``` py
def copy_paste_node(input_files):
    return {k: lambda v=v: copy_paste(v) for k, v in input_files.items()}

# `lambda:` becomes `lambda v=v:`
```

**Environment:**
- Kedro Version: 0.18.3
- Operating System: macOS
