### ISSUE TITLE
Add selected add-ons to the created project's metadata

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#3129]
## Description
This is a follow up ticket for #2522 
This can be done after the add-ons workflow is in its final iteration of design and implementation.
Once the user creates a new Kedro project with the project creation wizard or using the `--addons` flag. This information should be added to the user project's `pyproject.toml`
```toml
[tool.kedro]
package_name = "spaceflights"
project_name = "spaceflights"
project_version = "0.18.11"
add_ons = ["1,2,3"] #or ["Linting", "Documentation"] or ["1", "2", "3"] format can be decided later, in agreement with Design
```

This metadata can then me passed on to `kedro-telemetry`.
## Context
Write up in the comment of the spike ticket https://github.com/kedro-org/kedro/issues/2522#issuecomment-1747205967

## Possible Implementation
- Decide on how to add the add ons to the metadata - Should it be a string, list, list of strings, written in number form or as words?
> add_ons = ["1,2,3"] or ["Linting", "Documentation"] or ["1", "2", "3"] format can be decided later

This implementation has two things to be done -
1. Make sure when project is created, `add-ons` is added to the project's `pyproject.toml`
2. When project metadata is read, `add-ons` is allowed as a field. This change will go in `kedro/framework/startup.py`
