### ISSUE TITLE
Improve MemoryDataset copy_mode selection

### ISSUE THREAD

**Issue by inigohidalgo** [kedro-org/kedro#3551]
## Description

Following from discussion in [Slack](https://kedro-org.slack.com/archives/C03RKP2LW64/p1705942987626539)

The way MemoryDataset decides which of the 3 copy modes to use is very straightforward, but in my opinion is lacking 4 years after its original implementation.

If no parameter is passed, it uses the function [`_infer_copy_mode`](https://github.com/kedro-org/kedro/blob/e187dca1a5546a0a87f609682e87245f362e65f8/kedro/io/memory_dataset.py#L86C5-L86C21)

In the case of Pandas dataframes and (I think) Spark dataframes, this is the correct logic, but is too restrictive in its logic to make everything else deepcopy by default. 

This is a problem when using Ibis Tables, which are not serializable, as discussed here https://github.com/kedro-org/kedro/issues/2374#issuecomment-1593200758

The solution is simple: to add the dataset to the catalog and manually set it to be a MemoryDataset with copy_mode: assign, but this rapidly becomes cumbersome when passing tables between many nodes, and becomes an unmaintainable hell.

I would like to be able to influence the logic in _infer_copy_mode by either
- supplying a "mapping of default copy mode for datatype" (@deepyaman) 
- overriding the default memorydataset with a subclass

@noklam correctly pointed out this last one could be done using dataset factories like so

```yml
# catalog.yml

{_catch_all_}:
  type: my.own.MemoryDataset # with different _infer_copy_mode()
OR
  copy_mode: "assign"

OR

{table_name#_ibis}: # haven't used factories yet myself, quoting the syntax from memory
  type: MemoryDataset
  copy_mode: "assign"
```

But we all agreed this wasn't the most ergonomic way to do it, as it forces you to do it in every project.

I would welcome your thoughts on this or any solutions I may have missed (some sort of hook?)
