### ISSUE TITLE
Config validation

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3613]
## Description
Today I spoke to a user that had a very long and treacherous `parameters.yml` like this:

```yaml
sensors:
  sensor1:
    name: "Sensor 1"
    type: "temperature"
    stderr: 0.1
  sensor2:
    name: "Sensor 2"
    type: "humidity"
    stderr: 0.1
  sensor3:
    name: "Sensor 3"
    type: "temperature"
    stderr: 0.1
  sensor4:
    name: "Sensor 4"
    type: "temperature"
    stderr: 0.2
```

And so forth. So, there are several problems:

1. There's lots of repetition. The user mentioned that it would be ideal to be able to "inherit" in YAML, something like:

```yaml
_sensor:
  type: "<unknown>"
  stderr: 0.1

sensors:
  sensor1: ${_sensor}  # All defaults are taken
  sensor2: ${_sensor}
    stderr: 0.2  # Try to override default, but 💥 syntax error
```

2. It's unclear how to validate this YAML. We did a quick proof of concept combining OmegaConf and Pydantic v2:

```python
from omegaconf import OmegaConf
from pydantic import BaseModel

class Sensor(BaseModel):
    name: str
    sensor_type: str = "<unknown>"
    stderr: t.Optional[float] = 0.1

class Config(BaseModel):
    sensors: t.Dict[str, Sensor]

config = OmegaConf.load("conf/base/parameters.yml")
c = Config.validate(config)
print(c.sensors["sensor3"].stderr)
```

Which was cool! Because the defaults were filled from the `Sensor` model.

However, (2a) it's not clear how to keep the defaults in the YAML, which was desirable (although there's maybe a way to achieve that in Pydantic), (2b) it's not clear if this should be in `parameters.yml` or rather a custom `sensors.yml`, and most importantly, (2c) it's not clear how or where to perform such validation. There's no `after_config_loaded` hook.

I think the closest might be what kedro-mlflow does using `after_context_created` https://github.com/Galileo-Galilei/kedro-mlflow/blob/e88679938b1d4c7633c3f631f6b402ff11ab61fe/kedro_mlflow/framework/hooks/mlflow_hook.py#L78-L79 but then it's trying to inject the config in the `KedroContext` https://github.com/Galileo-Galilei/kedro-mlflow/blob/e88679938b1d4c7633c3f631f6b402ff11ab61fe/kedro_mlflow/framework/hooks/mlflow_hook.py#L129-L134, with all the problems discussed in #3214.

How can we better support this use case?

Paging @datajoely, @Galileo-Galilei

**Comment by astrojuanlu** [comment]
Tangentially related: https://github.com/kedro-org/kedro/issues/2481

**Comment by datajoely** [comment]
Regarding validation I would actually apply the Pydantic models to the functions bound in the node function - not couple it to the configuration system.

**Comment by Galileo-Galilei** [comment]
This is indeed a question that have been asked a couple of times. Apart from this specific use case (where it may make sense to have a specific configuration file as you suggest), my usual go to solution is to create a custom resolver,  which would look like this : 

```
_sensor:
  type: "<unknown>"
  stderr: 0.1

_sensor2:
  stderr: 0.2

sensors:
  sensor1: ${_sensor}  # All defaults are taken
  sensor2: ${merge_dict: _sensor, _sensor2} # in settings. py : register_new_resolver("merge_dict", lambda d1, d2: {**d1, **d2})
```

We could probably make the syntax easier with a more complex resolution logic (e.g. find if the key exists in a parent node to "automatically" check for a parent key with the same name (look for _parent_ on this page https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html).
