### ISSUE TITLE
Best practices for sharing configuration across multiple catalog files

### ISSUE THREAD

**Issue by sbrugman** [kedro-org/kedro#3625]
There are at least three dynamic techniques to define the Data Catalog currently in Kedro:

- [YAML anchors](https://docs.kedro.org/en/stable/data/data_catalog_yaml_examples.html#load-multiple-datasets-with-similar-configuration-using-yaml-anchors)
- (nested) [variable interpolation](https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#catalog
) through the OmegaConfigLoader.
- [Dataset factories](https://docs.kedro.org/en/stable/data/kedro_dataset_factories.html)

There is a common usage pattern for which even a combination of these three is not expressive enough to satisfactory specify the configuration.

## Scenario

Each of the pipelines consists of a set of nodes of limited distinct types, e.g. source (read only), intermediate (write local) and final (write to some database).

Multiple people are working on different pipelines, so the catalog is split in a file per pipeline:
```txt
conf/base/catalog/
    pipeline_a.yml
    pipeline_b.yml
    pipeline_c.yml
```
The split files provide overview and prevent conflicts when working in parallel.
So far so good. 

Rapidly, each of these files begins to look like:
```yaml
# Templates
_source_table: &source_table
  type: datasets.SourceTable
  read_only: true
  metadata:
    kedro-viz:
      layer: source

# More templates…

_output_table: &output_table
  type: datasets.ProductionDB
  database: constant
  mode: overwrite
  metadata:
    kedro-viz:
      layer: primary

# Datasets
a_ds1:
    <<: *source_table
    database: hello
    table: world

# More datasets…

a_ds_15:
   <<: *output_table
   table: foobar
```

Each file contains more or less the same YAML anchors, which [according to the specs](https://stackoverflow.com/a/18871178) cannot be shared across files. Is there another way to store this common information in a single file, instead in every single one of them - while keeping a single file per pipeline?

The variable interpolation perhaps?
Even though the OmagaConfigLoader can interpolate a dict, this (afaik) does not allow to partially pass a dict, such as we can do in Python (or with the anchors above):
```python
Source = {“read_only”: True}


my_table = {
   **source,
    “Database”: “db”
}
```

The dataset factories also do not support this pattern.
The following would be close, but is too restrictive:

```yaml
"{name}_source”:
  type: datasets.SourceTable
  read_only: true
  metadata:
    kedro-viz:
      layer: source
  Table: {name}
```

Restrictions: 
- All information needs to be in the dataset name. This is undesirable for long/badly names tables. Even more if the database name should be included too, and the layer information. The dataset name should be an alias.
- Flexibility to overwrite individual properties that we had with the YAML anchors seems not possible.

## Desiderata 

The user needs to be able to template catalog entries across multiple files. It must be possible to overwrite individual entries and it should be possible that the name is an alias.

**Comment by MigQ2** [comment]
Hi @sbrugman, I am having the same issue you mention here, where I want more flexibility and avoid copying common YML configs over and over but I don't seem to find an easy way in the current kedro ecosystem

Did you find any elegant solution?

I think playing with OmegaConf resolvers might make it work but it makes things quite unreadable and complicated

**Comment by MigQ2** [comment]
I am adding an interesting Slack discussion here, where the interaction between factories and OmegaConf resolvers is discussed, so that we can have it as a reference on this topic: 

https://linen-slack.kedro.org/t/22708331/hi-is-it-possible-to-use-a-dataset-factory-in-config-resolve

Initial message:

> Hi, is it possible to use a dataset factory in config resolver?
> An example:
>```yml
>"{name}_feature":
>  type: pandas.ParquetDataset
>  filepath: data/04_feature/{name}_feature.parquet
>  metadata:
>    pandera:
>      schema: ${pa.python:my_kedro_project.pipelines.feature_preprocessing.schemas.{name}_feature_schema}
>```
>The above gives me this:
>
>```
>omegaconf.errors.GrammarParseError: mismatched input '{' expecting BRACE_CLOSE
>    full_key: {name}_feature.metadata.pandera.schema
>    object_type=dict
>```

**Comment by sbrugman** [comment]
If `globals.yml` injects the YAML anchors in the same file under the hood, then that could work. Is that what you had in mind?

**Comment by astrojuanlu** [comment]
Unclear to me if YAML anchors can be shared. But variables and blocks of YAML definitely can. The way of using them deviates from normal YAML syntax though, and I don't think the "inheritance" provided by YAML anchors is supported in Omegaconf.

**Comment by ravi-kumar-pilla** [comment]
Hi @sbrugman , If I understand this correctly, we need a way to -
1. Have the ability to mention all the template/repeated information in a single file
2. The templated file should have the ability to be shared across multiple files
3. There should be a way to inject partial template information

Based on my understanding, you can use `globals.yml` and `variable interpolation` to succeed in (1) and (2). I think variable interpolation might not support partial injection. Have you tried Nested Interpolation or a custom Kedro hook for merging ?

**1. Use Nested Interpolation**

Instead of referencing a full dictionary, define individual fields separately.

  **Define Templates in catalog_template.yml**
  
  ```yaml
  _source_table:
    type: datasets.SourceTable
    read_only: true
    metadata: ${_source_metadata}
  
  _source_metadata:
    kedro-viz:
      layer: source
  ```

  **Use Interpolation in pipeline_a.yml**
  
  ```yaml
  a_ds1:
    type: ${_source_table.type}
    read_only: ${_source_table.read_only}
    metadata: ${_source_table.metadata}
    database: hello  # Overriding field
    table: world
  ```

**2. Use a Kedro Hook for Merging**: Not sure if it is recommended to modify catalog at this stage :(

  **Define Templates in catalog_template.yml**
  
  ```yaml
  _dataset_templates:
    source_table:
      type: datasets.SourceTable
      read_only: true
      metadata:
        kedro-viz:
          layer: source
    output_table:
      type: datasets.ProductionDB
      database: constant
      mode: overwrite
      metadata:
        kedro-viz:
          layer: primary
  ```

  **Reference the Template in pipeline_a.yml**
  
  ```yaml
  a_ds1:
    template: ${_dataset_templates.source_table}
    database: hello
    table: world
  ```

  **Implement a Hook to Merge Templates**
  
  ```python
  from kedro.framework.hooks import hook_impl
  from kedro.config import OmegaConfigLoader
  
  class CatalogTemplateHook:
      @hook_impl
      def after_context_created(self, context):
          # some way to modify catalog and merge template using OmegaConf
  ```

  a_ds1 will be expanded into:
  
  ```yaml
  a_ds1:
    type: datasets.SourceTable
    read_only: true
    metadata:
      kedro-viz:
        layer: source
    database: hello
    table: world
  ```

Do you think any of this will be helpful for your use case ? 

Thank you
