### ISSUE TITLE
Add automatic retry to GHA nightly build workflows

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#3652]
## Description
The nightly build and notification workflow creates a lot of spurious failure notification issues which are usually resolved on a re-run of the failed tests.
Proposal: Add an automatic re-run of the failed tests/entire test suite before it reaches the create issue for the failure of notification step so that only genuine failures create failure issues.

## Possible Implementation
I looked into this very briefly and saw these actions, but haven't tried it out yet. 
- https://github.com/marketplace/actions/retry-step
- https://github.com/marketplace/actions/retry-action

**Comment by ElenaKhaustova** [comment]
Checked the solutions possible in our case:

1. https://github.com/marketplace/actions/retry-step - will not work in our case as it works by re-running a command that you specify, so it will not work directly with other `uses` directives. This means it is most applicable when you are re-running explicit shell commands but not `workflows`.
2. https://www.thisdot.co/blog/how-to-retry-failed-steps-in-github-action-workflows - this solution seems the easiest in our case and can be applied at the `checks` level, so that we re-run not `all-checks` but only those that fail. The drawback is that you cannot easily set up re-run parameters (attempts, etc)
3. https://github.com/Wandalen/wretry.action - does seem to do the right thing but it's a bit harder to apply compared to 2nd option.

From the above decided to try two different solutions: 2 and 3

**Comment by ElenaKhaustova** [comment]
After checking 2 and 3 from the above, we've figured out that:

- both 2 and 3 allow retrying `steps` or `actions`;
- reusable workflows must be called as jobs: https://github.com/orgs/community/discussions/27362
- potentially, we can add a retry on one of three levels: `test-nightly-build.yml` (workflow level), `all-checks.yml` (workflow level) or for the checks itself, i.e. `unit-tests.yml`/`unit-tests.yml`, ... (steps level)

To make it work at the workflow level, we must also create actions from the workflows. So the plan is to start from the check and apply retry at the steps level.

**Comment by ElenaKhaustova** [comment]
The current working solution is tracking the job status at the level of the checks (`lint.yml`, `unit-tests.yml`, ..) and adding an extra retry job if the main job fails, see an example below.

```
jobs:
  lint:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Set up Python ${{ inputs.python-version }}
        continue-on-error: true
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache python packages
        continue-on-error: true
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{inputs.os}}-python-${{inputs.python-version}}
      - name: Install dependencies
        continue-on-error: true
        run: |
            make install-test-requirements
            make install-pre-commit
      - name: pip freeze
        continue-on-error: true
        run: pip freeze
      - name: Run linter
        continue-on-error: true
        run: make lint
  lint-retry:
    runs-on: ${{ inputs.os }}
    if: ${{ always() && needs.lint.outputs.status != 'success' }}
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{inputs.os}}-python-${{inputs.python-version}}
      - name: Install dependencies
        run: |
          make install-test-requirements
          make install-pre-commit
      - name: pip freeze
        run: pip freeze
      - name: Run linter
        run: make lint
```
