### ISSUE TITLE
Make credentials a resolver

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro#3811]
## Description

Make "credentials" a ``OmegaConf`` resolver, so injecting credentials in the catalog would look like : 

```yaml
# current injection
my_data:
    type: pandas.CSVDataset
    filepath: /path/to/data.csv
    credentials: my_credentials # a string which refer to a a section in credentials.yaml
```

```yaml
# new proposal
my_data:
    type: pandas.CSVDataset
    filepath: /path/to/data.csv
    credentials: ${credentials: my_credentials}
```

## Context

This makes looks like a pure technical refactoring, but actually I am expecting this to be an actual improvement for users, e.g. : 
- **improve readability** : credentials are hard to grasp because it does some magic relying on the template. As of our old kedro motto *[A sprinkle of magic is better than a spoonful of it](https://docs.kedro.org/en/0.17.7/12_faq/03_kedro_principles.html#a-sprinkle-of-magic-is-better-than-a-spoonful-of-it)*
- **define logic for empty credentials** : users will be able to handle "empty" credentials (often not provided when developing locally but necessary in production, this forces you to have empty keys during development), see https://github.com/kedro-org/kedro/issues/3634 for a user monkey patching credentials in ``settings.py``
- **pass credentials object instead of strings**: it is common to have some complicated credentials objects which are hard to express purely with a yaml description, see https://github.com/kedro-org/kedro/issues/1621
- **enable custom logic to fetch credentials**, which is often hardcoded in hooks right now : https://github.com/kedro-org/kedro/issues/2547 
- **improve sharing logic** : a credentials is just a normal python function. Passing it as a resolver would enable people to create their own credentials fetching logic and override kedro's just by installing a package provided by their org.
- **decouple the code of catalog and the config resolution**: all the logic currently lives in the Datacatalog class (see below) , which does not looks right. Moving this logic to the config would eventually helps https://github.com/kedro-org/kedro/issues/3659 if we want to go forward in this direction. 

Overall, this would likely be a general improvement with following of what is described here https://github.com/kedro-org/kedro/issues/1646 and has never been properly adressed, despite a bunch of discussions around this topic. 

## Possible Implementation

Move the logic from the catalog and the ``_get_credentials`` and ``_resolve_credentials``: 

https://github.com/kedro-org/kedro/blob/7237dc79e6b77475f6f1296f4fdd9d6aad3e1d11/kedro/io/data_catalog.py#L35-L58

https://github.com/kedro-org/kedro/blob/7237dc79e6b77475f6f1296f4fdd9d6aad3e1d11/kedro/io/data_catalog.py#L61-L83

to a resolver. 

## Possible Alternatives

Do nothing and keep the situation as is.
