### ISSUE TITLE
Add a note admonition about leveraging YAML anchors & aliases to avoid copypasting `metadata.kedro-viz.layer` in catalog

### ISSUE THREAD

**Issue by yury-fedotov** [kedro-org/kedro#4185]
## Description
[This section](https://docs.kedro.org/projects/kedro-viz/en/stable/kedro-viz_visualisation.html#visualise-layers) of docs provides a guide to adding `layers` to the visualization by defining them as follows:

```yaml
companies:
  type: pandas.CSVDataset
  filepath: data/01_raw/companies.csv
  metadata:
    kedro-viz:
      layer: raw
```

Also it gives the following example below:

```yaml
companies:
  type: pandas.CSVDataset
  filepath: data/01_raw/companies.csv
  metadata:
    kedro-viz:
      layer: raw

reviews:
  type: pandas.CSVDataset
  filepath: data/01_raw/reviews.csv
  metadata:
    kedro-viz:
      layer: raw

shuttles:
  type: pandas.ExcelDataset
  filepath: data/01_raw/shuttles.xlsx
  metadata:
    kedro-viz:
      layer: raw

...
```

## Context
In my projects I found it very helpful to use YAML anchors to save those 3 lines per layer into a variable like this:

```yaml
_raw_layer: &raw_layer
  metadata:
    kedro-viz:
      layer: 01_raw
```

And then reuse it like this:

```yaml
companies:
  type: pandas.CSVDataset
  filepath: data/01_raw/companies.csv
  <<: *raw_layer

reviews:
  type: pandas.CSVDataset
  filepath: data/01_raw/reviews.csv
  <<: *raw_layer

shuttles:
  type: pandas.ExcelDataset
  filepath: data/01_raw/shuttles.xlsx
  <<: *raw_layer
```

## Possible Implementation
What I propose to do it to add a small **note** admonition suggesting that YAML anchors & aliases can be a great fit here to avoid copypasting those 3 lines if you have e.g. 10 datasets defined in a layer.

By admonition I mean e.g. this:

<img width="951" alt="Screenshot 2024-06-24 at 10 35 00 PM" src="https://github.com/kedro-org/kedro/assets/102987839/94f51113-59b9-477d-a784-38be9f224ecf">

It can mention that this feature is not Kedro-specific at all and enabled by YAML format itself, but I think it can be helpful since this trick is highly reusable and can simplify large catalogs quite a lot for users unfamiliar with anchors & aliases in YAML.

> I do **not** propose to change the existing example which replicates those 3 lines 3 times.
> I think my suggestion better fits a note admonition.

## Checklist

- [ ] Include labels so that we can categorise your feature request
