### ISSUE TITLE
[Versioning]: Explore Kedro + DVC for versioning

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#4239]
## Description
At the current stage by versioning we assume mapping a single version number to the corresponding versions of parameters, I/O data, and code. So one is able to retrieve a full project state including data at any point in time.

The goal is to check if we can use [DVC](https://dvc.org/) to map a single version number to code, parameters, and I/O data within Kedro and how it aligns with Kedro’s workflow.

As a result, we expect a working example of kedro project used with DVC for versioning and some assumptions on:

- whether it solves the main task and what are the constraints;
- how easy is to set up;
- how the workflow looks like;
- whether any changes are required on the kedro side;
- what data formats are supported;
- how easy is to work with local/remote storage;

## Context
https://github.com/kedro-org/kedro/issues/4199

Relates to: https://github.com/kedro-org/kedro/issues/2691#issuecomment-2363967567

**Comment by aadarshsingh191198** [comment]
If I am not wrong, what we are asking for here is support in `kedro` for something similar to 
```
dvc stage add -n train -d train.py -d data \
          -o model.weights.h5
```
Ref: https://dvc.org/doc/use-cases/versioning-data-and-models/tutorial#automating-capturing

**Comment by ankatiyar** [comment]
# Kedro + DVC integration

I tried to integrate DVC into my Spaceflights Kedro project to check the extent of the versioning capabilities. The steps I followed are:

1. Initialise the Kedro project as a git repository: `git init`
2. Initialise the Kedro project as a DVC repository: `dvc init`

## Versioning data with `.dvc` files
Suppose, I have a dataset in my project: 
```yaml
companies:
  type: pandas.CSVDataset
  filepath: data/01_raw/companies.csv
```
* `dvc add data/01_raw/companies.csv` -> this generates the `companies.csv.dvc` file which can be committed to git. **Note:** You would need to update the `.gitignore` file provided by Kedro to make this work.
* `git commit -m "First commit"`
* `kedro run` - Intermediate and output datasets are generated
* `dvc add <paths of datasets that were generated>`
* `git add .` 
* `git commit -s -m "First run"`

### Scenario 1: I want to go back to a previous version of the data 
* Check which git commit I want to go back to 
* `git checkout HEAD~2 data/01_raw/companies.csv.dvc`
* `dvc checkout`

### Scenario 2: I want to store my data remotely
* `dvc remote add <name> <url>`: https://dvc.org/doc/user-guide/data-management/remote-storage
* `kedro run`: generates new data
* `git add .` and `git commit -m "Update"
* `dvc push`

### Scenario 3: I want to go back to a previous version of the data, stored remotely
* `git checkout <>`
* `dvc checkout`
* `dvc pull`


## Versioning with DVC Data Pipelines
The previous way does provide enough functionality to version datasets but there's still the following to consider
- Users must add all intermediate and output datasets to dvc manually 
- Parameters and code changes are not explicitly tracked 
- Can not track artefacts and metrics

### Define Kedro pipelines as DVC stages
- In `dvc.yaml`, we can define Kedro pipelines as follows
```yaml
stages:
  data_processing:
    cmd: kedro run --pipeline data_processing
    deps:
      - data/01_raw/companies.csv
      - data/01_raw/reviews.csv
      - data/01_raw/shuttles.xlsx
    outs:
      - data/02_intermediate/preprocessed_companies.pq
      - data/02_intermediate/preprocessed_shuttles.pq
      - data/03_primary/model_input_table.pq
  
  data_science:
    cmd: kedro run --pipeline data_science
    deps:
      - data/03_primary/model_input_table.pq
      outs:
      - data/06_models/regressor.pickle
```
- run the pipeline with `dvc repro`

### Scenario: One of the datasets is updated
- `dvc repro` will run only pipelines for which the output or the deps have changed

### Scenario: I want to track code changes
- Add code files to the `deps` in `dvc.yml`
```yaml
stages:
  data_processing:
    cmd: kedro run --pipeline data_processing
    deps:
      - data/01_raw/companies.csv
      - data/01_raw/reviews.csv
      - data/01_raw/shuttles.xlsx
      - src/space_dvc/pipelines/data_processing/nodes.py
      - src/space_dvc/pipelines/data_processing/pipeline.py
    outs:
      - data/02_intermediate/preprocessed_companies.pq
      - data/02_intermediate/preprocessed_shuttles.pq
      - data/03_primary/model_input_table.pq
```
- `dvc repro`
- `dvc push`

### Scenario: I want to track parameters
- Add parameters under `params` in `dvc.yml`
```yaml
data_science:
    cmd: kedro run --pipeline data_science
    deps:
      - data/03_primary/model_input_table.pq
      - src/space_dvc/pipelines/data_science/nodes.py
      - src/space_dvc/pipelines/data_science/pipeline.py
    params:
      - conf/base/parameters_data_science.yml:
        - model_options
    outs:
      - data/06_models/regressor.pickle
```
- `dvc repro`
- `dvc push`

### Scenario: I want to run the experiment with different parameters
- Change parameter in `parameters.yml`
- `dvc repro`: This will only run `data_science` pipeline
- `dvc params diff`: This will show you the comparison of parameters between runs

## Experiment tracking with DVCLive [WIP]
