### ISSUE TITLE
Rename MatplotlibWriter to MatplotlibDataset

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro#4524]
## Description

To be consistent with naming `kedro-datasets`, this ticket aims at renaming `MatplotlibWriter` to `MatplotlibDataset` (needs discussion on the final name)

## Context

https://github.com/kedro-org/kedro/issues/4473#issuecomment-2686336864

## Possible Implementation

- Create a deprecation warning for `MatplotlibWriter` about a possible renaming 
- Create a duplicate of `MatplotlibWriter` and name it as `MatplotlibDataset`
- Update instances of `MatplotlibWriter` with `MatplotlibDataset`
- Update docs
- Remove `MatplotlibWriter`

**Comment by astrojuanlu** [comment]
Can we actually close this in favour of https://github.com/kedro-org/kedro-plugins/issues/353 ? There's more context and discussion there

**Comment by JonathanLoscalzo** [comment]
https://docs.kedro.org/en/stable/tutorials/create_a_pipeline/
here, on the spaceflights tutorial, it is continue using the old name!

```
dummy_confusion_matrix:
  type: matplotlib.MatplotlibWriter
  filepath: data/08_reporting/dummy_confusion_matrix.png
  versioned: true
```
