### ISSUE TITLE
CSV Dataset append mode not working with expected args

### ISSUE THREAD

**Issue by maxschulz-COL** [kedro-org/kedro#4585]
## Description
When using a csv dataset, the below doesn't work

```yaml
model_metrics_aggregated:
  type: pandas.CSVDataset
  filepath: data/08_reporting/model_metrics_aggregated.csv
  save_args:
    mode: a
```

but this one does
```yaml
model_metrics_aggregated:
  type: pandas.CSVDataset
  filepath: data/08_reporting/model_metrics_aggregated.csv
  fs_args:
    open_args_save:
      mode: a
```

Why? From the docs it seems that the top one should be the route to go...
I used these docs: https://docs.kedro.org/projects/kedro-datasets/en/kedro-datasets-2.0.0.post1/api/kedro_datasets.pandas.CSVDataset.html

## Context
It annoyed me :) 

## Steps to Reproduce
Just use the dataset as described above

## Expected Result
Append to work by using the described commands

## Actual Result
No append

## Your Environment
Latest kedro
