### ISSUE TITLE
`kedro catalog list-patterns` lists user defined default pattern twice

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#4900]
## Description
`kedro catalog list-patterns` lists user defined `{default}` pattern twice when 

## Context
`{default}` is the pattern used as a runtime pattern at the catalog level since version 1.0.0rc1. When user add their own pattern with the same name the command outputs its twice.

## Steps to Reproduce
1. Set user user-defined pattern in the catalog
```yaml
"{default}":
  type: pandas.CSVDataset
	filepath: data/05_model_input/{default}.csv
```
2. `kedro catalog list-patterns`

## Expected Result
All patterns listed just once

## Actual Result
```console
- '{name}-{folder}#csv'
- '{name}_data'
- out-{dataset_name}
- '{dataset_name}#csv'
- in-{dataset_name}
- '{default}'
- '{default}'
```

## Your Environment
kedro, version 1.0.0rc1
