### ISSUE TITLE
Problems with loading CSVDatSet with no header

### ISSUE THREAD

**Issue by fanzipei** [kedro-org/kedro#943]
## Description
Hi, I meet one problem with CSVDataSet when the file contains no header. Here I will show how to reproduce it using the official example "pandas-iris".

## Context
I encounter this problem when loading a partitioned dataset with gzip compression. It is a little complex to add all gzip files with header lines. After I find this error, I do the testing on the example project and reproduce the error.

## Steps to Reproduce
1. Download the example project
`kedro new --starter=pandas-iris
`
2. Delete the header of iris.csv
3. Modify catalog.yml as (here I made 3 trials, I will explain the results later):
```
# Case 1
example_iris_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/iris.csv
  load_args:
    header: false
```
```
# Case 2
example_iris_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/iris.csv
  load_args:
    header: None
```
```
# Case 3
example_iris_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/iris.csv
  load_args:
    header: 0
```

## Expected Result
Load the iris.csv file with no header. 0, 1, 2, 3, ... are automatically generated as the column names. The expected behavior should be exactly the same with pd.read_csv('iris.csv', header=None)

## Actual Result
In case 1, it generates the error message as:

```
kedro.io.core.DataSetError: Failed while loading data from data set CSVDataSet(filepath=E:/work/kedro-example-iris/data/01_raw/iris.csv, load_args={'header': False}, protocol=file, save_args={'index': False}).
Passing a bool to header is invalid. Use header=None for no header or header=int or list-like of ints to specify the row(s) making up the column names
```
Following this error message, I change to case 2, and get the error message as:

```
kedro.io.core.DataSetError: Failed while loading data from data set CSVDataSet(filepath=E:/work/kedro-example-iris/data/01_raw/iris.csv, load_args={'header': None}, protocol=file, save_args={'index': False}).
header must be integer or list of integers
```
Following this error message, I change to case 3. This time it runs without error message, but when I check the data it reads, I find it does not assume there is no header by printing out the data on the first line of split_data.
```
def split_data(data: pd.DataFrame, example_test_data_ratio: float) -> Dict[str, Any]:
    print(data.head())
    data.columns = [
        "sepal_length",
        "sepal_width",
        "petal_length",
        "petal_width",
        "target",
    ]
   ...
```
It shows that 

```
   5.1  3.5  1.4  0.2  setosa
0  4.9  3.0  1.4  0.2  setosa
1  4.7  3.2  1.3  0.2  setosa
2  4.6  3.1  1.5  0.2  setosa
3  5.0  3.6  1.4  0.2  setosa
4  5.4  3.9  1.7  0.4  setosa
```
It seems it still takes the first line as the header.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): Kedro 0.17.5
* Python version used (`python -V`): python 3.8 and 3.6
* Operating system and version: Windows and CentOS

Thanks.
